# Generated by Django 4.1.7 on 2023-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questionquiz_quiz_response_questionquiz_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
