# Generated by Django 4.1.7 on 2023-03-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='FBE0Lq9wsgsw7AO6SBQk', max_length=20, unique=True),
        ),
    ]
