# Generated by Django 4.1.7 on 2023-03-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='uk1IbdQP7nOnCBLULoMu', max_length=20, unique=True),
        ),
    ]
