# Generated by Django 4.1.7 on 2023-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='9RGB7giJ9aAqneDIPA76', max_length=20, unique=True),
        ),
    ]
